// <auto-generated />
namespace Portfolio.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Product_NotMappedImage_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_NotMappedImage_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "202005070121165_Product_NotMappedImage_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
